config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'auth'
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end
  get 'pages/callback/:id/' => 'pages#callback'
  mount Attachinary::Engine => "/attachinary"

  resources :pages, only: [:show] do
  	resources :page_parts do
  		resources :contents
  	end
  end
  get 'contents/search_content' => 'pages#search', as: :search
  root 'pages#show', :id => '1'

  post '/email' => 'email#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
	has_attachment  :avatar, accept: [:jpg, :png, :gif]
	has_attachments :photos, maximum: 10, accept: [:jpg, :png, :gif]
	belongs_to :page_part, optional: true

	validates_presence_of :avatar, if: 'allow_photo?'
	validates_presence_of :photos, if: 'allow_photos?'
	validates_presence_of :title, if: 'allow_title?'
	validates_presence_of :body, if: 'allow_text?'
	validates_presence_of :body, if: 'allow_link?'

	def allow_photo?
  	self.page_part.allow_photo
	end

	def allow_title?
  	self.page_part.allow_title
	end

	def allow_link?
		self.page_part.allow_link
	end

	def allow_text?
  	self.page_part.allow_text
	end

	def allow_photos?
  	self.page_part.allow_photos
	end
end

app/models/page.rb
class Page < ApplicationRecord
	has_many :page_parts
end

app/models/page_part.rb
class PagePart < ApplicationRecord
	belongs_to :page, optional: true
	has_many :contents
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_action :set_page_part, only: [:new, :edit, :show, :create, :update, :destroy]

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = @page_part.contents.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to page_path(@page_part.page_id), notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: page_path(@page_part.page_id) }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to page_path(@page_part.page_id), notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: page_path(@page_part.page_id) }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to page_path(@page_part.page_id), notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    def set_page_part
      @page_part = PagePart.find(params[:page_part_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:body, :title, :link, :avatar, photos:[])
    end
end

app/controllers/email_controller.rb
class EmailController < ApplicationController
  def create
    EmailMailer.contact(email_params).deliver_now
  end

  private

  def email_params
    params.require(:email).permit(:name, :email, :phone, :description, :reason)
  end
end

app/controllers/page_parts_controller.rb
class PagePartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_page_part, only: [:show, :edit, :update, :destroy]
  before_action :set_page, only: [:new, :create, :show, :update]

  # GET /page_parts/1
  # GET /page_parts/1.json
  def show
  end

  # GET /page_parts/new
  def new
    @page_part = PagePart.new
  end

  # GET /page_parts/1/edit
  def edit
  end

  # POST /page_parts
  # POST /page_parts.json
  def create
    @page_part = @page.page_parts.new(page_part_params)
    respond_to do |format|
      if @page_part.save
        format.html { redirect_to @page, notice: 'Page part was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /page_parts/1
  # PATCH/PUT /page_parts/1.json
  def update
    respond_to do |format|
      if @page_part.update(page_part_params)
        format.html { redirect_to @page, notice: 'Page part was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /page_parts/1
  # DELETE /page_parts/1.json
  def destroy
    @page_part.destroy
    respond_to do |format|
      format.html { redirect_to page_parts_url, notice: 'Page part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page_part
      @page_part = PagePart.find(params[:id])
    end

    def set_page
      @page = Page.find(params[:page_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_part_params
      params.require(:page_part).permit(:name, :allow_creatable, :allow_photo, 
                                        :allow_title, :allow_text)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find(params[:id])
  end

  def search
    @searched_name = params[:name]
    @contents = []
    unless @searched_name.blank?
      @contents = Content.where("body like ?", "%#{@searched_name}%").or(
                  Content.where("title like ?", "%#{@searched_name}%"))
      @domain = request.domain
    end
  end
  def callback
    @content = Content.find(params[:id])
  end
  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:name)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def management
  end

  def engineering
  end

  def legal
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def footer
		@footer = Page.find_by(name: 'footer')
	end

	def footer_part
		@footer = Page.find_by(name: 'footer')
		@footer.page_parts[0]
	end

	def page_part(page, name)
		page.page_parts.each do |page_part|
			if page_part.name == name
				return page_part
			end 
		end
	end

	def redirect_page(name)
		pages = { 'Home Page' => 1, 'Client' => 2, 'Student' => 3,
							'Legal' => 4, 'Engineering' => 5, 'Management' => 6 }
		pages[name]
	end

	def page_clients?(page)
		page.name == 'client' unless page.nil? 	
	end

	def page_student?(page)
		page.name == 'student' unless page.nil?
	end

	def page_legal?(page)
		page.name == 'legal' unless page.nil?
	end

	def page_management?(page)
		page.name == 'management' unless page.nil?
	end

	def page_engineering?(page)
		page.name == 'engineering' unless page.nil?
	end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/page_parts_helper.rb
module PagePartsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contents/_form.html.erb
<%= form_for(content, url: {controller: 'contents', action: action}) do |f| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if page_part.allow_title %>
    <div class="field">
      <%= f.label :title, "Título" %>
      <%= f.text_field :title %>
    </div>
  <% end %>

  <% if page_part.allow_text %>
    <div class="field">
      <%= f.label :body, "Texto" %>
      <%= f.text_area :body, cols: 70,  rows:15 %>
    </div>
  <% end %>

  <% if page_part.allow_link %>
    <div class="field">
      <%= f.label :link, "Link" %>
      <%= f.text_field :link %>
    </div>
  <% end %>

  <% if page_part.allow_photo %>
    <div class="field">
      <%= f.attachinary_file_field :avatar %>
    </div>
    <p>Faça upload de uma imagem por vez!</p>
  <% end %>

  <% if page_part.allow_photos %>
    <div class="field">
      <%= f.attachinary_file_field :photos %>
    </div>
    <p>Faça upload de uma imagem por vez!</p>
  <% end %>

  <div class="actions">
    <%= f.submit "Criar Conteúdo" %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editando Conteúdo</h1>

<%= render 'form', content: @content, action: 'update', page_part: @page_part %>

<%= link_to 'Voltar', page_page_part_path(@page_part.page_id, @page_part) %>

app/views/contents/new.html.erb
<div class="form-content">
	<h1>Novo Conteúdo</h1>

	<%= render 'form', content: @content, action: 'create', page_part: @page_part %>

  <%= link_to 'Voltar', page_page_part_path(@page_part.page_id, @page_part)  %>
</div>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @content.body %>
</p>

<p>
  <strong>Title:</strong>
  <%= @content.title %>
</p>

<p>
  <strong>Order:</strong>
  <%= @content.order %>
</p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>

app/views/layouts/_accordion.html.erb
<section class="accordion accordion--<%= component %>" id="areas_de_atuacao">
  <div class="container section">
    <h2 class="title title--<%= component %>"> <%= title %> </h2>
    <div class="separator separator--<%= component %>"></div>
    <% if user_signed_in? %>
      <%= link_to 'Editar Seção', page_page_part_path(section.page_id, section) %>
    <% end %>
    <div class="atuacao section__wrapper">
      <% section.contents.each do |content| %>
        <div
          class="accordion__card accordion__card--<%= component %>"
          style="background-image:
          url( <%= content.avatar.fullpath if content.avatar? %> )">

          <h3 class="accordion__title"><%= content.title %></h3>
          <p class="accordion__description">
            <%= content.body %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/layouts/_candidates_form.html.erb
<section class= "<%= component %>" >
	<div class="title">
		<h2 class="text">QUER ENTRAR PARA O BONDE?</h2>
		<div class="line"></div>
	</div>

	<%= form_for :record, :html => {:class => 'form'} do |f| %>

		<div class="box-left">
			<div class="input-group">
				<%= f.label :nome, "NOME"  %>
				<%= f.text_field :name, class: "text-field" %>
			</div>
			<div class="input-group">
				<%= f.label :email, "EMAIL" %>
				<%= f.text_field :email, class: "text-field" %>
			</div>
			<div class="input-group">
				<%= f.label :phone, "TELEFONE" %>
				<%= f.text_field :phone, class: "text-field" %>
			</div>
		</div>
		<div class="box-right">
			<%= f.label :description, "QUER ENTRAR PARA O BONDE?" %>
			<%= f.text_area :description, placeholder: "QUER ENTRAR PARA O BONDE?", class: "textarea" %>
			<%= f.text_area :description, class: "textarea textarea-small" %>
		</div>
		<div class="submit-box">
			<%= button_tag( :class => "submit-button") do %>
				<span>ENVIAR</span>
  			<i class="fa fa-2x  fa-check" aria-hidden="true"></i>
  		<% end %>
		</div>
	<% end %>
</section>

app/views/layouts/_carousel.html.erb
<section class="container section carousel">
  <div class="carousel__title carousel__title--<%= component %>">
    Projetos Anteriores
  </div>
  <hr class="sep sep--<%= component %>">
  <div style="color: black">
  <% if user_signed_in? %>
    <%= link_to 'Editar Slides', page_page_part_path(slides.page_id, slides  ) %>
  <% end %>
  </div>
  <div class="carousel__wrapper">
    <svg class="carousel__prev" width="39" height="78" xmlns="http://www.w3.org/2000/svg" version="1.1">
      <polyline points="30 6 6 39 30 72" stroke="white" stroke-width="6"
        fill="none" stroke-linejoin="miter"/>
    </svg>
    <svg class="carousel__next" width="39" height="78" xmlns="http://www.w3.org/2000/svg" version="1.1">
      <polyline points="6 6 30 39 6 72" stroke="white" stroke-width="6"
        fill="none" stroke-linejoin="miter"/>
    </svg>
    <ul class="carousel__controls">
      <% slides.contents.each_with_index do |content, i| %>
        <li class="carousel__control <%= i == 0 ? 'carousel__control--active' : '' %> ">
          <%= i %>
        </li>
      <% end %>
    </ul>

    <% slides.contents.each_with_index do |content, index| %>
      <div
        id="modal"
        class="carousel__slide <%= index == 0 ? 'carousel__slide--active' : '' %>"
        style="background-image: url(<%= content.photos[0].fullpath %>  )"
        data-modal="<%= content.id %>"
      >
        <div class="hero__title">
          <%= content.title %>
        </div>

        <div class="hero__text" style="height: 120px; overflow: hidden;">
          <%= content.body %>
        </div>
        <span>. . .</span>
        <div style="padding-top: 30px;">
          CLIQUE PARA SABER MAIS
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/layouts/_contact.html.erb
<section class="contact" id="contato">
  <div class="title">
    <div class="head">CONTATO</div>
    <div class="line"></div>
    <% page_part(page, 'Contato').contents.each do |content| %>
      <p class="description">
        <%= content.body %>
      </p>
    <% end %>
    <% if user_signed_in? %>
      <%= link_to 'Editar Parágrafos', page_page_part_path(page, page_part(page, 'Contato')) %>
    <% end %>
  </div>
  <div class="container">
    <div class="address-map">
      <div class="adress">
        Setor Comercial Sul Q. 1 BL 1 BL A Union Building SL 901 <br>
        Brasília, DF, 70297-400 <br><br>
        projetosintegrada.com.br <br><br>
        (61) 3966-1661 <br><br>
        Horário de Funcionamento:<br>
        De Segunda à Sexta <br>
        de 14:00 às 18:00
      </div>
      <div class="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2714.6366720797573!2d-47.88809651948805!3d-15.799946212773586!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x935a3ade001c4747%3A0x77b7705a44409bf2!2sProjetos+Consultoria+Integrada!5e0!3m2!1spt-BR!2sus!4v1499981450533" width="500" height="350" frameborder="0" id="big" style="border:0" allowfullscreen></iframe>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3839.0848742082494!2d-47.889294285625546!3d-15.799478089048092!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x935a3ade001c4747%3A0x77b7705a44409bf2!2sProjetos+Consultoria+Integrada!5e0!3m2!1spt-BR!2sbr!4v1500074615399" width="400" height="300" frameborder="0" id="small"  style="border:0" allowfullscreen></iframe>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3839.0848742082494!2d-47.889294285625546!3d-15.799478089048092!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x935a3ade001c4747%3A0x77b7705a44409bf2!2sProjetos+Consultoria+Integrada!5e0!3m2!1spt-BR!2sbr!4v1500074615399" width="200" height="300" frameborder="0" id="xsmall"  style="border:0" allowfullscreen></iframe>
        <div class="border-red border-top-right"></div>
        <div class="border-red border-down-left"></div>
      </div>
    </div>

    <div class="form-container">
      <%= form_for :email, :url => {:controller => "email", :action => "create"}, :html => {action: email_path, :class => 'form'} do |f| %>

  			<div class="input-group">
  				<%= f.label :name, "NOME", class: "label-inline"  %>
  				<%= f.text_field :name, class: "text-field" %>
  			</div>
  			<div class="input-group">
  				<%= f.label :email, "EMAIL", class: "label-inline" %>
  				<%= f.text_field :email, class: "text-field" %>
  			</div>
  			<div class="input-group">
  				<%= f.label :phone, "TELEFONE", class: "label-inline" %>
  				<%= f.text_field :phone, class: "text-field" %>
  			</div>
    	   <div class="input-group">
           <%= f.label :description, "MENSAGEM", class: "label-inline" %>
           <%= f.text_area :description, class: "textarea" %>
    	   </div>
         <div class="reason">
          <%= f.label :reason, "ASSUNTO", class: "label-inline",
              style:"margin-bottom: 20px;" %>
          <div class="radio-group">
            <input type="radio" id="option-one" name="selector" checked="checked">
            <label for="option-one" class="radio-item">PROJETOS</label>
            <input type="radio" id="option-two" name="selector">
            <label for="option-two" class="radio-item">DEIXE SEU DEPOIMENTO</label>
            <input type="radio" id="option-three" name="selector">
            <label for="option-three" class="radio-item">OUTROS</label>
          </div>

         </div>
    		<div class="submit-box">
    			<%= button_tag( :class => "submit-button") do %>
    				<span>ENVIAR</span>
      			<i class="fa fa-2x  fa-check" aria-hidden="true"></i>
      		<% end %>
    		</div>
    	<% end %>
    </div>
  </div>
  <div class="note">
    Não encontrou o que precisava aqui na Projetos Consultoria Integrada? <br>
    <a href="https://contrateumaempresajunior.com.br/">Clique aqui</a>
    para conhecer outras empresas que podem ajudar!
  </div>
</section>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="social-medias">
		<a href="https://www.instagram.com/projetosintegrada/ ">
			<div class="circle">
				<%= fa_icon "instagram", class: "fa-4x", style:" padding-top: 8px;" %>
			</div>
		</a>
		<a href="https://www.facebook.com/projetosintegrada/ ">
			<div class="circle">
				<%= fa_icon "facebook", class: "fa-4x", style:" padding-top: 10px;" %>
			</div>
		</a>
	</div>
	<div class="adress">
		Setor Comercial Sul Q, 1 BL A Union Building SL 901 <br>
		Brasília, DF, 70297-400 <br>
		projetosintegrada.com.br <br>
		(61) 3966-1661
		<hr>
	</div>

	<div class="partners-list">
		<h2>PARCEIROS</h2>
			<% footer_part.contents.each do |content| %>
				<% content.photos.each do |photo| %>
					<%= cl_image_tag( photo.fullpath, width: '60px', height: '30px' ) %>
				<% end %>
			<% end %>
			<% if user_signed_in? %>
				<%= link_to 'Editar Lista de parceiros',
					page_page_part_path(footer, footer_part) 
				%>
			<% end %>
	</div>

</footer>

app/views/layouts/_form.html.erb
<section class= "<%= component %>" >
	<div class="title">
		<h2 class="text">QUER ENTRAR PARA O BONDE?</h2>
		<div class="line"></div>
	</div>

	<%= form_for :record, :html => {:class => 'form'} do |f| %>

		<div class="box-left">
			<div class="input-group">
				<%= f.label :nome, "NOME"  %>
				<%= f.text_field :name, class: "text-field" %>
			</div>
			<div class="input-group">
				<%= f.label :email, "EMAIL" %>
				<%= f.text_field :email, class: "text-field" %>
			</div>
			<div class="input-group">
				<%= f.label :phone, "TELEFONE" %>
				<%= f.text_field :phone, class: "text-field" %>
			</div>
		</div>
		<div class="box-right">
			<%= f.label :description, "QUER ENTRAR PARA O BONDE?" %>
			<%= f.text_area :description, placeholder: "QUER ENTRAR PARA O BONDE?", class: "textarea" %>
			<%= f.text_area :description, class: "textarea textarea-small" %>
		</div>
		<div class="submit-box">
			<%= button_tag( :class => "submit-button") do %>
				<span>ENVIAR</span>
  			<i class="fa fa-2x  fa-check" aria-hidden="true"></i>
  		<% end %>
		</div>
	<% end %>
</section>

app/views/layouts/_hamburguer_sub_items.html.erb
<% items.each do |key, value| %>
	<a href="<%= key %>">
		<li><%= value %></li>
	</a>
<% end %>
	<%= link_to do %>
		<li><a href="https://medium.com/@PCINTEGRADA">BLOG</a></li>
	<% end %>

app/views/layouts/_header.html.erb
<header class="header">
	<%= link_to root_path, class: "logo" do %>
		<%= image_tag("Logotipo PCI - horizontal.svg", size: "210x100", alt: "PCI") %>
	<% end %>
	<div class="item"> <%= link_to 'SOBRE A PCI', page_path(redirect_page('Home Page'), :anchor => "sobre_a_pci") %> </div>
	<div class="item">
		<%= link_to page_path(redirect_page('Home Page'), :anchor => "mej") do %>
      MOVIMENTO <br> EMPRESA JÚNIOR
    <% end %>
	</div>
	<div class="item"> <%= link_to 'CONTATO', page_path(redirect_page('Home Page'), :anchor => "contato") %> </div>
	<div class="buscador item">
    <%= form_tag search_path, method: :get do %>
      <div class="inner-addon right-addon">
        <%= image_submit_tag 'search.svg', class: 'button-search search' %>
        <%= text_field_tag :name, @searched_name, style:'direction: rtl',
        																					placeholder: 'BUSCAR',
        																					class: 'seach-input' %>
      </div>
    <% end %>
  </div>

  <!-- Menu Hamburguer -->
  <div class="mobile-nav">
    <div class="menu-btn" id="menu-btn">
      <div></div>
      <span></span>
      <span></span>
      <span></span>
    </div>

    <div class="responsive-menu">
      <ul>
        <li>
          <%= link_to 'SOBRE A PCI', page_path(redirect_page('Home Page'),
                                               :anchor => "sobre_a_pci") %>
        </li>

        <%= link_to page_path(redirect_page('Home Page'), :anchor => "mej") do %>
          <li>MOVIMENTO EMPRESA JÚNIOR</li>
        <% end %>

        <li>
          <%= link_to 'CONTATO', page_path(redirect_page('Home Page'),
                                           :anchor => "contato") %>
        </li>

        <div class="buscador">
          <%= form_tag search_path, method: :get do %>
            <div class="inner-addon right-addon">
              <%= text_field_tag :name, @searched_name, style:'direction: rtl',
                                                        placeholder: 'BUSCAR',
                                                        class: 'seach-input' %>
              <%= image_submit_tag 'search.svg', class: 'button-search search' %>
            </div>
          <% end %>
        </div>

        <div class="secundary-items">

          <% if page_clients? @page or page_engineering? @page or
                page_management? @page or page_legal? @page %>
          	<%= render 'layouts/hamburguer_sub_items',
          							items: clients = {
          								'/pages/2#servicos' => "SERVIÇOS",
                          '/pages/2#partners' => "QUEM CONFIA NA GENTE" } %>
          <% end %>

          <% if page_student? @page %>
          	<%= render 'layouts/hamburguer_sub_items',
          							items: students = {
          								'#areas_de_atuacao' => "ÁREAS DE ATUAÇÃO",
                          '#quem_passou_por_aqui' => "QUEM PASSOU POR AQUI",
                          '#processo_seletivo' => "PROCESSO SELETIVO" } %>
          <% end %>

        </div><!-- ./secundary-items -->
      </ul>
    </div> <!-- ./responsive-menu -->
  </div> <!-- ./mobile-nav -->
</header>

app/views/layouts/_modal.html.erb
<div id="info" class="modal">
  <div class="modal__wrapper">
    <!-- Empty tags have their content dynamically inserted via js -->
    <h1 class="modal__title"></h1>
    <hr>
    <div class="modal__text"></div>
    <span class="modal__label">CLIQUE PARA AMPLIAR AS FOTOS.</span>
    <div class="modal__images"></div>
  </div>
</div>
<div id="images" class="modal">
  <svg class="modal__prev" width="39" height="78" xmlns="http://www.w3.org/2000/svg" version="1.1">
    <polyline points="30 6 6 39 30 72" stroke="white" stroke-width="6"
    fill="none" stroke-linejoin="miter"/>
  </svg>
  <img class="modal__preview">
  <div class="modal__list"></div>
  <svg class="modal__next" width="39" height="78" xmlns="http://www.w3.org/2000/svg" version="1.1">
    <polyline points="6 6 30 39 6 72" stroke="white" stroke-width="6"
    fill="none" stroke-linejoin="miter"/>
  </svg>
</div>

app/views/layouts/_sub_header.html.erb
<div class="sub-header">
	<% items.each do |key, value| %>
  	<div class="item"> <a href="<%= key %>"><%= value %></a> </div>
	<% end %>
	<div class="item"> <a href="https://medium.com/@PCINTEGRADA">BLOG</a></div>
</div>

app/views/page_parts/edit.html.erb
<h1>Editing Page Part</h1>

<%= render 'form', page_part: @page_part, action: 'update' %>

app/views/page_parts/new.html.erb
<h1>New Page Part</h1>

<%= render 'form', page_part: @page_part, action: 'create' %>

<%= link_to 'back', page_path(@page) %>

app/views/pages/search.html.erb
<div class="results">
	<div class="container section">
	<div class="buscador">
    <%= form_tag search_path, method: :get do %>
      <div class="inner-addon right-addon">
        <%= image_submit_tag 'search.svg', class: 'button-search search' %>
        <%= text_field_tag :name, @searched_name, style:'direction: rtl',
        																					placeholder: 'BUSCAR',
        																					class: 'seach-input' %>
      </div>
    <% end %>
  </div>
	<h2>RESULTADOS</h2>
	<div class="separator"></div>
		<% @contents.each do |content|%>
			<div class="item">
				<%= link_to page_path(content.page_part.page_id) do %>
  				<% if content.title.nil? %>
  					<div class="item-title"> <%= @searched_name %></div>
  				<% else %>
  					<div class="item-title"> <%= content.title %> </div>
  				<% end %>
				<% end %>
				<div class="item-link">
					<%= link_to "#{@domain}/#{content.page_part.page.name}",
											 page_path(content.page_part.page_id) %>
				</div>
				<div class="item-text"> <%= content.body %> </div>
			</div>
		<% end %>
	</div>
</div>